"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import dotenv

from .base_settings import *

print()
import socket
print (f"socket.gethostname()={socket.gethostname()}")

print("load production settings")
from .production_settings import *

print()